### ISSUE TITLE
Problem in PyQt5 in Mac Arm

### ISSUE THREAD

**Issue by charlesneimog** [DigiScore/neoscore#104]
Hi, I am trying to install neoscore in MacOS arm and I have this problem:

``` bash 

Collecting PyQt5<6.0.0,>=5.15.6 (from neoscore)
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/5b/c1r85my926j5nlg4v1t0ds7c0000gs/T/pip-build-env-jz41tduj/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/5b/c1r85my926j5nlg4v1t0ds7c0000gs/T/pip-build-env-jz41tduj/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/5b/c1r85my926j5nlg4v1t0ds7c0000gs/T/pip-build-env-jz41tduj/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 586, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/5b/c1r85my926j5nlg4v1t0ds7c0000gs/T/pip-install-13gv9q9y/pyqt5_f54d8115468f40e89ee2e3a060bc8f38/project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/5b/c1r85my926j5nlg4v1t0ds7c0000gs/T/pip-build-env-jz41tduj/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/5b/c1r85my926j5nlg4v1t0ds7c0000gs/T/pip-build-env-jz41tduj/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/5b/c1r85my926j5nlg4v1t0ds7c0000gs/T/pip-build-env-jz41tduj/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
``` 

The problem is that `PyQt5` does not provide wheel for Macs Arm. My question is, how difficult would be to update `PyQt5` to `PyQt6` in neoscore?

I am working in [py4pd](https://www.charlesneimog.com/py4pd/) which uses neoscore. The aim is to build some score tools like we have in OpenMusic using PureData. But problems like this can be very problematic for people that use Puredata but do not use Python. etc...

If I can help in something let me know.

**Comment by ajyoon** [comment]
Closing this as there's no further action on our end besides existing long-term roadmap work.
